name: Shared API Build and Test Jobs

on:
  workflow_call: 
    outputs:
      build-result:
        description: "Build result"
        value: ${{ jobs.build-and-test.outputs.result }}

jobs:
  build-and-test:
    name: "Build and Test"
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.set-output.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./video-uploader-api

      - name: Build the solution
        run: dotnet build --configuration Release --no-restore
        working-directory: ./video-uploader-api

      - name: Run unit tests
        run: dotnet test --filter "Category=Unit"
        working-directory: ./video-uploader-api

      - name: Run integration tests
        run: dotnet test --filter "Category=Integration"
        working-directory: ./video-uploader-api

      - name: Set output
        id: set-output
        run: echo "result=success" >> $GITHUB_OUTPUT